galaxy_info:
  author: Matheus Macan
  description: Install Wordpress CloudBook
  company: Cloudbooks

  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: 2.9


  galaxy_tags: []


dependencies: []
