Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.vm.define "master" do |master|
      master.vm.box = "ubuntu/bionic64"
      master.vm.network "forwarded_port", guest: 8080, host: 8080
    # config.vm.provision :ansible do |ansible|
    #   ansible.limit = "all"
    #   ansible.playbook = "../ansible/playbook.yml"
    # end
    end
    config.vm.network "private_network", type: "dhcp"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "3072"
      vb.cpus = "3"
    end
  end
  